import Head from 'next/head';
import React from 'react';
import axios from 'axios';
import Image from 'next/image';
import Header from '../components/header';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [photos, setPhotos] = React.useState([]);

  React.useEffect(() => {
    (async function loadDefaults() {
      const res = await axios.get('/api/photos/');
      setPhotos(res.data);
    }());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Momento - Royalty free images and pictures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <p className={styles.description}>
          Momento is a decentralized platform for freely usable images.
          <br />
          {/* <a>Why Share?</a> */}
          {/* <a>License</a> */}

        </p>

        <div className={styles.grid}>
          {photos.map((photo) => (
            <div key={photo.originalCid}>
              <Image src={`https://bafybeigyr7pxdbgqolaux64keh7fls5wqeh3wxqjm5hmy4iz5us65umqfa.ipfs.dweb.link/${photo.fileName}`} width="400" height="400" />
              {photo.originalCid}
            </div>
          ))}
        </div>
      </main>

    </div>
  );
}
